export const TYPES = {
    TYPE_NUMBER: 'TYPE_NUMBER',
    TYPE_STRING: 'TYPE_STRING',
    TYPE_BOOL: 'TYPE_BOOL',
    TYPE_LABEL: 'TYPE_LABEL',
    TYPE_SYMBOL: 'TYPE_SYMBOL',
    TYPE_STACK_SLOT: 'TYPE_STACK_SLOT',
}
